M48
; DRILL file KiCad 10.0.5 date 2026-09-19T00:00:00+08:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-19T00:00:00+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,Plated,1,5,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.200
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.250
%
G90
G05
T1
X81.0Y-60.6
X94.5Y-64.7
X104.17Y-55.69
X104.69Y-55.99
T2
X29.65Y-53.5
X36.7Y-34.6
X42.8Y-39.0
M30
