"""eco --- ECO 文书链：校验 + 生成（#K2-357）。文书由本模块生成/校验；LLM 只填工程判断字段。"""
from __future__ import annotations
import glob, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ECO_DIR = os.path.join(ROOT, "docs", "ECO")
REQ = {1: "变更内容", 2: "变更理由", 3: "影响网清单", 4: "受影响文档", 5: "回滚方式", 6: "验收判据"}
TEMPLATE = """# {id} · {title}

- **状态**：{status}
- **提出日**：{date} ｜ **提出者**：eda_eng ｜ **关联裁定**：{authority}

## 1 变更内容（改什么）
{what}

## 2 变更理由（为什么）
{why}

## 3 影响网清单（逐条网名）
{nets}

## 4 受影响文档
{docs}

## 5 回滚方式
{rollback}

## 6 验收判据（数字）
{criteria}

## 7 施工方案（拆线清单 / 重布方法与顺序 / 风险）
{plan}

## 8 过程质量记录（判据 / 读数 / 时间 / 执行者）
| 步 | 判据 | 读数 | 时间 | 执行者 |
|---|---|---|---|---|
{records}

## 9 对单式核对（ECO-方案-图-实物）
{consistency}

LEGAL-ESCALATION: none
OWNER-ITEMS: 0
"""


def check_form(path):
    t = open(path, encoding="utf-8").read()
    miss = []
    if not re.search(r"^-\s*\*\*状态\*\*", t, re.M):
        miss.append("status_line")
    for n, title in REQ.items():
        if not re.search(r"^##\s*%d\s+%s" % (n, title), t, re.M):
            miss.append("sec%d:%s" % (n, title))
    sec6 = re.search(r"^##\s*6\s+验收判据.*?(?=^##\s*7|\Z)", t, re.M | re.S)
    if not (sec6 and re.search(r"\d", sec6.group(0))):
        miss.append("sec6:no_numeric_criterion")
    if not re.search(r"`[A-Za-z0-9_+#/\.-]+`", t):
        miss.append("sec3:no_named_nets")
    return {"eco": os.path.basename(path), "complete": not miss, "missing": miss}


def check_all(eco_dir=ECO_DIR):
    files = sorted(glob.glob(os.path.join(eco_dir, "ECO-K2-*.md")))
    reg = open(os.path.join(eco_dir, "REGISTER.md"), encoding="utf-8").read() if os.path.isfile(
        os.path.join(eco_dir, "REGISTER.md")) else ""
    skel = {f: os.path.isfile(os.path.join(eco_dir, f)) for f in ("README.md", "_TEMPLATE-ECO.md", "REGISTER.md")}
    ecos = []
    for f in files:
        r = check_form(f)
        m = re.match(r"(ECO-K2-\d+)", r["eco"])
        r["registered"] = bool(m and m.group(1) in reg)
        if not r["registered"]:
            r["missing"].append("not_in_REGISTER"); r["complete"] = False
        ecos.append(r)
    ok = all(skel.values()) and all(e["complete"] for e in ecos)
    return {"artifact": "eda_eng_eco_check", "skeleton": skel, "ecos": ecos,
            "verdict": "PASS" if ok else "FAIL",
            "rule": "#K2-357 sec.2: form complete + registered is a precondition for a board change"}


def render(spec):
    """spec = dict of engineering-judgment fields -> ECO markdown (generated by code, not by hand)."""
    return TEMPLATE.format(**spec)
