variables { name: "lane_p0" domain: [0, 3] }
variables { name: "lane_p1" domain: [0, 3] }
variables { name: "lane_p2" domain: [0, 3] }
variables { name: "lane_p3" domain: [0, 3] }
constraints {
  all_diff {
    exprs { vars: [0] coeffs: [1] }
    exprs { vars: [1] coeffs: [1] }
    exprs { vars: [2] coeffs: [1] }
    exprs { vars: [3] coeffs: [1] }
  }
}
constraints {
  linear {
    vars: [0, 1]
    coeffs: [1, -1]
    domain: [-9223372036854775808, -1]
  }
}
